//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVCA2Reference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanadianAddressResponse", Namespace="http://www.serviceobjects.com")]
    public partial class CanadianAddressResponse : object
    {
        
        private AVCA2Reference.CanadianAddressInfo CanadianAddressInfoField;
        
        private AVCA2Reference.Error ErrorField;
        
        private string[] DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AVCA2Reference.CanadianAddressInfo CanadianAddressInfo
        {
            get
            {
                return this.CanadianAddressInfoField;
            }
            set
            {
                this.CanadianAddressInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AVCA2Reference.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string[] Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanadianAddressInfo", Namespace="http://www.serviceobjects.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AVCA2Reference.CanadianAddressInfoV2))]
    public partial class CanadianAddressInfo : object
    {
        
        private string AddressField;
        
        private string Address2Field;
        
        private string MunicipalityField;
        
        private string ProvinceField;
        
        private string PostalCodeField;
        
        private string TimeZoneField;
        
        private string AddressNumberFragmentField;
        
        private string StreetNameFragmentField;
        
        private string StreetTypeFragmentField;
        
        private string DirectionalCodeFragmentField;
        
        private string UnitTypeFragmentField;
        
        private string UnitNumberFragmentField;
        
        private string IsPOBoxField;
        
        private string BoxNumberFragmentField;
        
        private string StationInfoField;
        
        private string DeliveryModeField;
        
        private string DeliveryInstallationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Municipality
        {
            get
            {
                return this.MunicipalityField;
            }
            set
            {
                this.MunicipalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TimeZone
        {
            get
            {
                return this.TimeZoneField;
            }
            set
            {
                this.TimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AddressNumberFragment
        {
            get
            {
                return this.AddressNumberFragmentField;
            }
            set
            {
                this.AddressNumberFragmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string StreetNameFragment
        {
            get
            {
                return this.StreetNameFragmentField;
            }
            set
            {
                this.StreetNameFragmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string StreetTypeFragment
        {
            get
            {
                return this.StreetTypeFragmentField;
            }
            set
            {
                this.StreetTypeFragmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DirectionalCodeFragment
        {
            get
            {
                return this.DirectionalCodeFragmentField;
            }
            set
            {
                this.DirectionalCodeFragmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string UnitTypeFragment
        {
            get
            {
                return this.UnitTypeFragmentField;
            }
            set
            {
                this.UnitTypeFragmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string UnitNumberFragment
        {
            get
            {
                return this.UnitNumberFragmentField;
            }
            set
            {
                this.UnitNumberFragmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string IsPOBox
        {
            get
            {
                return this.IsPOBoxField;
            }
            set
            {
                this.IsPOBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string BoxNumberFragment
        {
            get
            {
                return this.BoxNumberFragmentField;
            }
            set
            {
                this.BoxNumberFragmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string StationInfo
        {
            get
            {
                return this.StationInfoField;
            }
            set
            {
                this.StationInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DeliveryMode
        {
            get
            {
                return this.DeliveryModeField;
            }
            set
            {
                this.DeliveryModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string DeliveryInstallation
        {
            get
            {
                return this.DeliveryInstallationField;
            }
            set
            {
                this.DeliveryInstallationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.serviceobjects.com")]
    public partial class Error : object
    {
        
        private string TypeField;
        
        private string TypeCodeField;
        
        private string DescField;
        
        private string DescCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DescCode
        {
            get
            {
                return this.DescCodeField;
            }
            set
            {
                this.DescCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanadianAddressInfoV2", Namespace="http://www.serviceobjects.com")]
    public partial class CanadianAddressInfoV2 : AVCA2Reference.CanadianAddressInfo
    {
        
        private string CorrectionsField;
        
        private string CorrectionsDescField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Corrections
        {
            get
            {
                return this.CorrectionsField;
            }
            set
            {
                this.CorrectionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CorrectionsDesc
        {
            get
            {
                return this.CorrectionsDescField;
            }
            set
            {
                this.CorrectionsDescField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanadianAddressResponseV2", Namespace="http://www.serviceobjects.com")]
    public partial class CanadianAddressResponseV2 : object
    {
        
        private AVCA2Reference.CanadianAddressInfoV2 CanadianAddressInfoV2Field;
        
        private AVCA2Reference.Error ErrorField;
        
        private string[] DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AVCA2Reference.CanadianAddressInfoV2 CanadianAddressInfoV2
        {
            get
            {
                return this.CanadianAddressInfoV2Field;
            }
            set
            {
                this.CanadianAddressInfoV2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AVCA2Reference.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string[] Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanadianAddressResponseV2_Bulk", Namespace="http://www.serviceobjects.com")]
    public partial class CanadianAddressResponseV2_Bulk : object
    {
        
        private string StatusMessageField;
        
        private string RecordsSentField;
        
        private string RecordsProcessedField;
        
        private string EnoughTransactionsBeforeProcessingField;
        
        private string ProcessingDurationField;
        
        private string MessageField;
        
        private AVCA2Reference.CanadianAddressInfoV2_List[] CanadianAddressInfoV2_ListField;
        
        private AVCA2Reference.Error ErrorField;
        
        private string DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusMessage
        {
            get
            {
                return this.StatusMessageField;
            }
            set
            {
                this.StatusMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RecordsSent
        {
            get
            {
                return this.RecordsSentField;
            }
            set
            {
                this.RecordsSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RecordsProcessed
        {
            get
            {
                return this.RecordsProcessedField;
            }
            set
            {
                this.RecordsProcessedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EnoughTransactionsBeforeProcessing
        {
            get
            {
                return this.EnoughTransactionsBeforeProcessingField;
            }
            set
            {
                this.EnoughTransactionsBeforeProcessingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ProcessingDuration
        {
            get
            {
                return this.ProcessingDurationField;
            }
            set
            {
                this.ProcessingDurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AVCA2Reference.CanadianAddressInfoV2_List[] CanadianAddressInfoV2_List
        {
            get
            {
                return this.CanadianAddressInfoV2_ListField;
            }
            set
            {
                this.CanadianAddressInfoV2_ListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AVCA2Reference.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanadianAddressInfoV2_List", Namespace="http://www.serviceobjects.com")]
    public partial class CanadianAddressInfoV2_List : object
    {
        
        private AVCA2Reference.CanadianAddressResponseV2 CanadianAddressResponseV2Field;
        
        private AVCA2Reference.CanadianAddressV2_Bulk_Input InputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AVCA2Reference.CanadianAddressResponseV2 CanadianAddressResponseV2
        {
            get
            {
                return this.CanadianAddressResponseV2Field;
            }
            set
            {
                this.CanadianAddressResponseV2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AVCA2Reference.CanadianAddressV2_Bulk_Input Input
        {
            get
            {
                return this.InputField;
            }
            set
            {
                this.InputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanadianAddressV2_Bulk_Input", Namespace="http://www.serviceobjects.com")]
    public partial class CanadianAddressV2_Bulk_Input : object
    {
        
        private string AddressField;
        
        private string Address2Field;
        
        private string IDField;
        
        private string LanguageField;
        
        private string MunicipalityField;
        
        private string PostalCodeField;
        
        private string ProvinceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipality
        {
            get
            {
                return this.MunicipalityField;
            }
            set
            {
                this.MunicipalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="AVCA2Reference.IValidateCanada2")]
    public interface IValidateCanada2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_QUERYGETXM" +
            "L", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_QUERYGETXM" +
            "LResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_QUERYGETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_GETXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_GETXMLResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_GETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_GETJSON", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_GETJSONRes" +
            "ponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_GETJSONAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_POST", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress_POSTRespon" +
            "se")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_POSTAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddress", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddressAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_QUERYGET" +
            "XML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_QUERYGET" +
            "XMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponseV2")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_QUERYGETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_GETXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_GETXMLRe" +
            "sponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponseV2")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_GETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_GETJSON", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_GETJSONR" +
            "esponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponseV2")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_GETJSONAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_POST", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_POSTResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponseV2")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_POSTAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_POSTXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_POSTXMLR" +
            "esponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponseV2")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_POSTXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2Response")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2Async(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_QUERYGETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_QUERYGETXMLAsync(string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_GETXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_GETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_GETXMLAsync(string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_GETJSON", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_GETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_GETJSONAsync(string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_POST", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce_POSTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_POSTAsync(string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ce", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianMunicipalityProvin" +
            "ceResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvinceAsync(string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_QUERYGETXMLRe" +
            "sponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_QUERYGETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_GETXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_GETXMLRespons" +
            "e")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_GETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_GETJSON", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_GETJSONRespon" +
            "se")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_GETJSONAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_POST", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress_POSTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_POSTAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddress", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ParseCanadianAddressResponse")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddressAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_Bulk_POS" +
            "T", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_Bulk_POS" +
            "TResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponseV2_Bulk")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2_Bulk> ValidateCanadianAddressV2_Bulk_POSTAsync(string Input, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_Bulk_POS" +
            "TXML", ReplyAction="http://www.serviceobjects.com/IValidateCanada2/ValidateCanadianAddressV2_Bulk_POS" +
            "TXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CanadianAddressResponseV2_Bulk")]
        System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2_Bulk> ValidateCanadianAddressV2_Bulk_POSTXMLAsync(string Input, string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IValidateCanada2Channel : AVCA2Reference.IValidateCanada2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ValidateCanada2Client : System.ServiceModel.ClientBase<AVCA2Reference.IValidateCanada2>, AVCA2Reference.IValidateCanada2
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ValidateCanada2Client() : 
                base(ValidateCanada2Client.GetDefaultBinding(), ValidateCanada2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DOTSAVCA2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidateCanada2Client(EndpointConfiguration endpointConfiguration) : 
                base(ValidateCanada2Client.GetBindingForEndpoint(endpointConfiguration), ValidateCanada2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidateCanada2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ValidateCanada2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidateCanada2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ValidateCanada2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidateCanada2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_QUERYGETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddress_QUERYGETXMLAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_GETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddress_GETXMLAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_GETJSONAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddress_GETJSONAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddress_POSTAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddress_POSTAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianAddressAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_QUERYGETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2_QUERYGETXMLAsync(Address, Address2, Municipality, Province, PostalCode, Language, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_GETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2_GETXMLAsync(Address, Address2, Municipality, Province, PostalCode, Language, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_GETJSONAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2_GETJSONAsync(Address, Address2, Municipality, Province, PostalCode, Language, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_POSTAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2_POSTAsync(Address, Address2, Municipality, Province, PostalCode, Language, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2_POSTXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2_POSTXMLAsync(Address, Address2, Municipality, Province, PostalCode, Language, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2> ValidateCanadianAddressV2Async(string Address, string Address2, string Municipality, string Province, string PostalCode, string Language, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2Async(Address, Address2, Municipality, Province, PostalCode, Language, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_QUERYGETXMLAsync(string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianMunicipalityProvince_QUERYGETXMLAsync(Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_GETXMLAsync(string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianMunicipalityProvince_GETXMLAsync(Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_GETJSONAsync(string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianMunicipalityProvince_GETJSONAsync(Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvince_POSTAsync(string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianMunicipalityProvince_POSTAsync(Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ValidateCanadianMunicipalityProvinceAsync(string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ValidateCanadianMunicipalityProvinceAsync(Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_QUERYGETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ParseCanadianAddress_QUERYGETXMLAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_GETXMLAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ParseCanadianAddress_GETXMLAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_GETJSONAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ParseCanadianAddress_GETJSONAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddress_POSTAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ParseCanadianAddress_POSTAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponse> ParseCanadianAddressAsync(string Address, string Address2, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.ParseCanadianAddressAsync(Address, Address2, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2_Bulk> ValidateCanadianAddressV2_Bulk_POSTAsync(string Input, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2_Bulk_POSTAsync(Input, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AVCA2Reference.CanadianAddressResponseV2_Bulk> ValidateCanadianAddressV2_Bulk_POSTXMLAsync(string Input, string LicenseKey)
        {
            return base.Channel.ValidateCanadianAddressV2_Bulk_POSTXMLAsync(Input, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSAVCA2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSAVCA2))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/AVCA2/api.svc/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ValidateCanada2Client.GetBindingForEndpoint(EndpointConfiguration.DOTSAVCA2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ValidateCanada2Client.GetEndpointAddress(EndpointConfiguration.DOTSAVCA2);
        }
        
        public enum EndpointConfiguration
        {
            
            DOTSAVCA2,
        }
    }
}
